spring.application.name=discovery-server

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false 
#ce service est le serveur Eureka, donc il ne doit pas essayer de s’enregistrer lui-même comme un client.